version: '1'
services:
  app:
    container_name: light-saas-landing-page
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./node_modules:/app/node_modules
      - .:/app
    environment:
      - HOSTNAME=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
